name: MATLAB CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Run tests
        uses: matlab-actions/run-tests@v2
        with:
          source-folder: matlab
          select-by-folder: tests
          test-results-junit: test-results/results.xml
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: junit
          path: test-results/results.xml
